---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-parent-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: cicd
spec:
  project: default
  source:
    repoURL: https://github.com/theautomation/kubernetes-gitops.git
    targetRevision: main
    path: deploy/argocd/child-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      allowEmpty: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
