---
- name: Update package list
  ansible.builtin.dnf:
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Upgrade packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"
