---
- name: Test namespace {{ item.namespace }}
  ansible.builtin.include_tasks: namespace.yaml
  when: item.namespace is defined

- name: Download manifest from github and apply to the k3s cluster
  ansible.builtin.include_tasks: deploy.yaml
  when: '"github" in item.source'

- name: Validate if pods of DaemonSet are running | {{ item.name }}
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "democratic-csi"
    label_selectors:
      - "app.kubernetes.io/name=democratic-csi"
  register: pod_list
  until: pod_list|json_query('resources[*].status.phase')|unique == ["Running"]
  retries: 20
  delay: 5
