---
- name: Download manifest from github and apply to the k3s cluster
  when: ansible_hostname == hostvars[groups["k3s_master"][0]]["ansible_hostname"]
  block:
    - name: Download | {{ item.name }}
      ansible.builtin.get_url:
        url: "{{ github_infra_manifests_url }}/{{ item.name }}.yaml"
        dest: "{{ temp_dir }}/{{ item.name }}.yaml"
        mode: "0664"

    - name: Apply | {{ item.name }}
      kubernetes.core.k8s:
        apply: true
        state: present
        src: "{{ temp_dir }}/{{ item.name }}.yaml"
        validate:
          fail_on_error: false

- name: Validate if pod is ready | {{ item.name }}
  kubernetes.core.k8s_info:
    kind: Pod
    name: metallb-controller
    namespace: metallb-system
    label_selectors:
      - "app.kubernetes.io/name=metallb"
      - "app.kubernetes.io/component=controller"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
  run_once: true

- name: Read metallb-addresspool template file and apply to the k3s cluster
  kubernetes.core.k8s:
    state: present
    template: "metallb-addresspool.yaml.j2"
  run_once: true
