---
- name: Test namespace {{ item.namespace }}
  ansible.builtin.include_tasks: namespace.yaml
  when: item.namespace is defined

- name: Download manifest from github and apply to the k3s cluster
  ansible.builtin.include_tasks: deploy.yaml

- name: Validate if pod is ready | {{ item.name }}
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ item.namespace }}"
    label_selectors:
      - app.kubernetes.io/name={{ labels.name }}
      - app.kubernetes.io/component={{ labels.component }}
      - app.kubernetes.io/instance={{ labels.instance }}
      - app.kubernetes.io/part-of={{ labels.part_of }}
    wait: true
    wait_condition:
      type: Ready
      status: "True"
  loop_control:
    loop_var: labels
  with_items:
    - {
        name: "vaultwarden",
        component: "server",
        instance: "production",
        part_of: "vaultwarden",
      }
