---
- name: Test namespace {{ item.namespace }}
  ansible.builtin.include_tasks: namespace.yaml
  when: item.namespace is defined

- name: Download manifest from github and apply to the k3s cluster
  ansible.builtin.include_tasks: deploy.yaml

- name: Validate if pod is ready | {{ item.name }}
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ item.namespace }}"
    label_selectors:
      - "app.kubernetes.io/name=ser2net"
      - "app.kubernetes.io/instance=rfxcom"
    wait: true
    wait_condition:
      type: Ready
      status: "True"