---
- name: Play for the desired state of the proxmox servers
  hosts: proxmox
  gather_facts: true
  remote_user: root
  become: true
  vars:
    ansible_user: root
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"

    - name: Update apt repo and cache on
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: dist

    - name: Set timezone
      community.general.timezone:
        name: "{{ system_timezone }}"
      when: (system_timezone is defined) and (system_timezone != "Your/Timezone")
