# Clusterwide, change namespace is allowed

kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: container-image-registry-credentials
  namespace: tools
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    .dockerconfigjson: AgAAjkm0Ug59wrA9l3I1Ku3bE9L6X054IqfaMs4QbzYncwa/yDUV6cAIT3CJQd3u8MCeh7GjR1HHtwcQ3bFHNCHQjaTYetHg4wWxlzXqjl9bwDjawhXU5uf4SS6+5E0mPYCocIX9IVzC4cgXuTl7KFu4+6dTkHUnrMc/zFD0DUropy/IrjB6i0I3l3r+2AiG+/HjGAE4NKay9eiAnwKxddDXD5OlVdH3U+CW289FMLty1XXgGBBGfRYAgonmazlz04m2AGQjy9kimPicL2FnWEbY3RNWzAfbvsuMTRLOni3m9lDL9uDKYfA813eH1qkoonTM2/55v5kIVZIQ35IadPqjKGPfYCnVe50PNgeo61s8d5xZBtUl8U6o7i5WOD9w3GoKscu7P78152APj53qbUc4v4lS52fp6mrU+3zccda0k34NpQ77zaUfH+tlXNTsHYCwlKPwjDJjjvL/F4IoTvtrXX14RN9A0Ff73thaJUu2hbNYfdD0gxALiMiQ1qwLWQFgiE3Iryy19joYS3vSuSbnrZAOeoSKftpMOr/Hpb5n72/WLPHGXU1Q11HjHzQyNrKkVp0Fz/a9riuPOEaF7sYGgdhKaON5k6QGhvbVt8yWZ9uVvot4/sa/BGKaB0q5CfuvjoD1Q5ThlBhYfLl8g8MJOCItAsy6AfdeT0cqUzwiTfPoS5N8GuIhCnNlNJe7GprUW+z55H/rzQf5zpK+yJCAaa/b6VpeJYeiN6jjgBMtixct7kNyk7tYGzp/9B9YLPj5MdNTzDnLFIvFh2qmJomGD1ZNM0SPKUcjprtTYMa8ax3HwUzEzlVajs3zRb6mDrZfxekdE9KLhTMjze5bsKxyKFkI+kCwq4k1tI2uoNs3suVtvL9t5ZQVHRdjX4oKHlgG0XNWMw==
  template:
    type: kubernetes.io/dockerconfigjson
    metadata:
      name: container-image-registry-credentials
      namespace: tools
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
