# Clusterwide, changing namespace is allowed

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: container-image-registry-credentials
  namespace: home-automation
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    .dockerconfigjson: AgDc5ngddSK4gqNr8dOcreSx4DMxkqdK7X9A+WA+/gDX8JLsX9mHYqzXHPdUHHjPWQTEHNlz3V4YX2F+dV/V6CPuDod8XQlDIYh6cMH1l1vlExKO/TDTy1deVZ2eJfJDhc7tpuETCLjnAmCgUD13DG2wLGfeFA8A72fGrNwAOTrYxg2M8mf8u6NSvuRHd+eyyORx3K/pRkSebF7+qWdh8g77Z0HLyzM/AaG4lO8odqpRSq1c+7gGP7bUfro8GMO7YWhmuh1X44HiurCT90GBnmKJb/E7sd1kCX+ZJ/GRdRz1xW0a5qL96gevG5dZS27F2WIHmgNhPSGlYKUdS5QxmztPveKVBETFpaL5qgkJz24sAhNc7JxjRZBqLB1qCyCpK4S6dV32B+SyYxde90Ka+jkdnZf2IQJ+AJPOdTmpLWmJ+JmdU8hPLJHKW6zKpnm5gH1PZqk+lL/kysvT2M/G2pcE/gQAG4S7ga1BGU9AsMKGF98eis6700wWANvL/BgmtqafUMVbNmJPdxxI3kU5fktbeSy9eAiUcCnsF49LrrHyfInk2SRFt9z7m57eyurCXEieBjiAxZ/TlwxWKMLzXfjmvRd+bUmcvzoAEL3/x6+ucw9HkkNtvx/sF8mL9h2pYEK48l0YRfkBStGfxnBS7u/9W5yK+NFX/D8yMeIp0GaSsVKzqAH1vOoHFtmdLURUylNhXgZRA5shHV9ZrPcVCJkv8wSpyF5msykTVNNENFmLT47utEHdkSHh0JnEvBhK0J8tDy4EHPPJzPnh7GJZX0QUOHoyULewLqmTiTa6DXYtTUhEybDGpYGnXH7Ora6+K1aBLuWZ3EOLsF6MRMTzvbOEivLB2WpKtMICE+bqm9b+nBtRFwRlezsYI1mTWm4tfRxzfyxPxDDFIlTIKQLBnPbEU1vLT5TKZnWP9WpLAIPgBA==
  template:
    type: kubernetes.io/dockerconfigjson
    metadata:
      name: container-image-registry-credentials
      namespace: home-automation
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: container-image-registry-credentials
  namespace: tools
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    .dockerconfigjson: AgDc5ngddSK4gqNr8dOcreSx4DMxkqdK7X9A+WA+/gDX8JLsX9mHYqzXHPdUHHjPWQTEHNlz3V4YX2F+dV/V6CPuDod8XQlDIYh6cMH1l1vlExKO/TDTy1deVZ2eJfJDhc7tpuETCLjnAmCgUD13DG2wLGfeFA8A72fGrNwAOTrYxg2M8mf8u6NSvuRHd+eyyORx3K/pRkSebF7+qWdh8g77Z0HLyzM/AaG4lO8odqpRSq1c+7gGP7bUfro8GMO7YWhmuh1X44HiurCT90GBnmKJb/E7sd1kCX+ZJ/GRdRz1xW0a5qL96gevG5dZS27F2WIHmgNhPSGlYKUdS5QxmztPveKVBETFpaL5qgkJz24sAhNc7JxjRZBqLB1qCyCpK4S6dV32B+SyYxde90Ka+jkdnZf2IQJ+AJPOdTmpLWmJ+JmdU8hPLJHKW6zKpnm5gH1PZqk+lL/kysvT2M/G2pcE/gQAG4S7ga1BGU9AsMKGF98eis6700wWANvL/BgmtqafUMVbNmJPdxxI3kU5fktbeSy9eAiUcCnsF49LrrHyfInk2SRFt9z7m57eyurCXEieBjiAxZ/TlwxWKMLzXfjmvRd+bUmcvzoAEL3/x6+ucw9HkkNtvx/sF8mL9h2pYEK48l0YRfkBStGfxnBS7u/9W5yK+NFX/D8yMeIp0GaSsVKzqAH1vOoHFtmdLURUylNhXgZRA5shHV9ZrPcVCJkv8wSpyF5msykTVNNENFmLT47utEHdkSHh0JnEvBhK0J8tDy4EHPPJzPnh7GJZX0QUOHoyULewLqmTiTa6DXYtTUhEybDGpYGnXH7Ora6+K1aBLuWZ3EOLsF6MRMTzvbOEivLB2WpKtMICE+bqm9b+nBtRFwRlezsYI1mTWm4tfRxzfyxPxDDFIlTIKQLBnPbEU1vLT5TKZnWP9WpLAIPgBA==
  template:
    type: kubernetes.io/dockerconfigjson
    metadata:
      name: container-image-registry-credentials
      namespace: tools
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
