---
- name: Download manifest from github and apply to the k3s cluster
  when: ansible_hostname == hostvars[groups["k3s_master"][0]]["ansible_hostname"]
  block:
    - name: Download manifest | {{ item.name }}
      ansible.builtin.get_url:
        force: true
        url: "{{ github_infra_manifests_url }}/{{ item.name }}.yaml"
        dest: "{{ temp_dir }}/{{ item.name }}.yaml"
        mode: "0664"

    - name: Apply manifest | {{ item.name }}
      kubernetes.core.k8s:
        apply: true
        state: present
        src: "{{ temp_dir }}/{{ item.name }}.yaml"
        validate:
          fail_on_error: false
          strict: false
