kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: test-and-build-image
  namespace: devops
spec:
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: https://github.com/theautomation/home-assistant.git
        - name: revision
          value: main
        - name: deleteExisting
          value: "true"

    - name: check-code-style
      taskRef:
        name: prettier
      runAfter:
        - fetch-repo
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: args
          value:
            - --config
            - ".prettierrc.yaml"
            - --ignore-path
            - "./.prettierignore.yaml"
            - --check
            - "./src/config/**/*.yaml"

    - name: check-yaml-style
      taskRef:
        name: yaml-lint
      runAfter:
        - fetch-repo
      workspaces:
        - name: shared-workspace
          workspace: shared-data
      params:
        - name: args
          value: ["."]

    - name: check-hass-config-latest
      taskRef:
        name: home-assistant
      runAfter:
        - check-code-style
        - check-yaml-style
      workspaces:
        - name: home-assistant-code
          workspace: shared-data
      params:
        - name: args
          value:
            - --script
            - "check_config"
            - --config
            - "./src/config/"

    - name: check-hass-config-dev
      taskRef:
        name: home-assistant
      runAfter:
        - check-code-style
        - check-yaml-style
      workspaces:
        - name: home-assistant-code
          workspace: shared-data
      params:
        - name: containerImage
          value: "homeassistant/home-assistant:dev"
        - name: args
          value:
            - --script
            - "check_config"
            - --config
            - "./src/config/"

    - name: check-hass-config-beta
      taskRef:
        name: home-assistant
      runAfter:
        - check-code-style
        - check-yaml-style
      workspaces:
        - name: home-assistant-code
          workspace: shared-data
      params:
        - name: containerImage
          value: "homeassistant/home-assistant:beta"
        - name: args
          value:
            - --script
            - "check_config"
            - --config
            - "./src/config/"

---
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  name: home-assistant-build
  namespace: devops
spec:
  pipelineRef:
    name: test-and-build-image
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
