kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: home-assistant
  namespace: devops
spec:
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: https://github.com/theautomation/home-assistant.git
        - name: revision
          value: main
        - name: deleteExisting
          value: "true"

    - name: buildah
      taskRef:
        name: buildah
      runAfter:
        - fetch-repo
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE
          value: docker-registry.devops.svc:5000/$(context.pipelineRun.namespace)/$(context.pipelineRun.name)
        - name: DOCKERFILE
          value: ./deploy/container/Containerfile
        - name: TLSVERIFY
          value: "false"
        - name: FORMAT
          value: "docker"

    # - name: check-code-style
    #   taskRef:
    #     name: prettier
    #   runAfter:
    #     - fetch-repo
    #   workspaces:
    #     - name: source
    #       workspace: shared-data
    #   params:
    #     - name: args
    #       value:
    #         - --config
    #         - ".prettierrc.yaml"
    #         - --ignore-path
    #         - "./.prettierignore.yaml"
    #         - --check
    #         - "./src/config/**/*.yaml"

    # - name: check-yaml-style
    #   taskRef:
    #     name: yaml-lint
    #   runAfter:
    #     - fetch-repo
    #   workspaces:
    #     - name: shared-workspace
    #       workspace: shared-data
    #   params:
    #     - name: args
    #       value: ["."]

    # - name: rename-example-secret
    #   taskRef:
    #     name: rename-secret
    #   runAfter:
    #     - check-code-style
    #     - check-yaml-style
    #   workspaces:
    #     - name: home-assistant-code
    #       workspace: shared-data

    # - name: check-hass-config-latest
    #   taskRef:
    #     name: home-assistant
    #   runAfter:
    #     - rename-example-secret
    #   workspaces:
    #     - name: home-assistant-code
    #       workspace: shared-data
    #   params:
    #     - name: containerImage
    #       value: "homeassistant/home-assistant:latest"
    #     - name: args
    #       value:
    #         - --script
    #         - "check_config"
    #         - --config
    #         - "./src/config/"

    # - name: check-hass-config-dev
    #   taskRef:
    #     name: home-assistant
    #   runAfter:
    #     - rename-example-secret
    #   workspaces:
    #     - name: home-assistant-code
    #       workspace: shared-data
    #   params:
    #     - name: containerImage
    #       value: "homeassistant/home-assistant:dev"
    #     - name: args
    #       value:
    #         - --script
    #         - "check_config"
    #         - --config
    #         - "./src/config/"

    # - name: check-hass-config-beta
    #   taskRef:
    #     name: home-assistant
    #   runAfter:
    #     - rename-example-secret
    #   workspaces:
    #     - name: home-assistant-code
    #       workspace: shared-data
    #   params:
    #     - name: containerImage
    #       value: "homeassistant/home-assistant:beta"
    #     - name: args
    #       value:
    #         - --script
    #         - "check_config"
    #         - --config
    #         - "./src/config/"
