---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-gitops
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: cicd
spec:
  project: default
  source:
    repoURL: https://github.com/theautomation/kubernetes-gitops.git
    targetRevision: main
    path: deploy/k8s
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
