---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: home-assistant-config-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage-server.lan
    path: "/r10_8tb/services/home-assistant/config"
  mountOptions:
    - nfsvers=4.0
    - hard

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-config-pvc
  namespace: prd-ext
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-assistant
  namespace: prd-ext
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k8s-worker-01
      containers:
        - name: home-assistant
          image: homeassistant/home-assistant:stable
          securityContext:
            privileged: true
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: home-assistant-config
              mountPath: /config
          resources:
            limits:
              cpu: 1
              memory: 4G
            requests:
              cpu: 1
              memory: 1G
      volumes:
        - name: home-assistant-config
          persistentVolumeClaim:
            claimName: home-assistant-config-pvc

---
kind: Service
apiVersion: v1
metadata:
  name: home-assistant
  namespace: prd-ext
spec:
  selector:
    app: home-assistant
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8123

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: home-assistant
  namespace: prd-ext
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx-prd-ext
  rules:
    - host: home-assistant.theautomation.nl
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 80
  tls:
    - hosts:
        - home-assistant.theautomation.nl
      secretName: home-assistant.theautomation.nl-tls
