---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-drone-server-data
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-drone-server-data
    volumeAttributes:
      portal: storage-server-lagg.lan:3260
      iqn: iqn.2005-10.org.freenas.ctl:drone-server-data
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-drone-server-data
  namespace: devops
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-iscsi-manual-csi"
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: pv-iscsi-drone-server-data

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: drone-server-secret
  namespace: devops
spec:
  encryptedData:
    DRONE_GITHUB_CLIENT_ID: AgCYM7K6a+KrooUE1Zcf0MG8KhnWaZEg5H2+Zfp4MC/TyGxUkco4++fu/iwoIvmanYrCb+vppOfUrgGuTFWNj0n7+uEYk5uiNXsZLUAtoKClmDGrzwrxIeTfC3/sG3r84Kn8u3INXR2xSSevi0sbRAoOTtFn+G4K0B+iyZgND7MsbYupihnjTpzk+gDT5ROQwkL++RQrqcsTXLcNHnR+UJOojDL+HD/KiLbbR8LTwsEtB7JCtc94wj9rj0O6x/KuW1fIy5IL3BLMpviPtad6+uXChLi3/+dSqa6PWUPx1nO0k+8UYK1J8HHU5O3qVgMxxrNlT7HJq839aWb5xzTUk3G/Wi/Rr/vn4h+9+tEvAorwRxurX3yMkO6Yyfa1uJyif4fwT/gDAMMDj+SyzK3jn5FOPddc/aTjv/HHueQrWo9ErKPUOjKW7o/ril7OCXJ9dCfXGG7wTu7mJaBMrJdjOgAcm0OW/hEts6k7s+E5KH32zgkd7HPixIJuYpnNfPHbpeo5v5DPYOpveY5kv/NGRkZwmN5IlwP1buHBsSX4NYhJTcRLRRaXH05BKJtbgbvGzRaVGl5ThxmA/lERrCKWPqX9G3hi6w/fjZlW10CzbDAsDcqiiJJ7c1SybqknGMFH9oFR9+ukOKge2YJTrE1D33xv6cLogriLgZojKUVVES+O85KAzUXWszJNAzzdM6EMwz/IwbHLIvj3P4/LW/73vRef6uqNhw==
    DRONE_GITHUB_CLIENT_SECRET: AgC6ehEAnvaMNs+Uews1hzhGMHMbE7lX+5qX7fADpK8nebUBHq2HWU5uNCY7hV9OEdTQiFDujyGeYyULpI2kdnBZZ495NkxjcOo0VRMP2wxQIpBAzQ64o010a7nHlByOeebSxddqNdzTKBIdCIU5y/QaorQN4ozRdsaxQA9Bu49FRLgPRcxdjaVtwCnbHIPTTqi3mxOTCRDlddpuE9ZFtK36HYe/GKjgI7VRg3wqSIK3dOLzTgDvEpswRI94ofHAdOzqOkyaPaBPyXQNp0z/C8QtfkH8+/ZBk7hvzclPi+ztQ9ays/wYzeWog1sUAlUtvjqFCvHFrkr0K34HVfOqPWRzH/8GWl3quT0cXw4FcfawqiVphe6CXhGdOQAexNXVbsCyoY14/LoyRmgZL6BmTW4ZJCVlbDmtfPfVY95JTI55oWpks6EXfEcuprucd3RWUTikZFkDmizcbNDbJjAG3uTv+lyCft1jGnJDxnVmiEFOJV8WygMP7q6NAdsyNr8beDIK3zNXSWfxybGz4SXcliFnS49sfGffL8G+E523tUD2UC6h6BHa1uMaYrEVWfnxN3AUymhfj9wJAOnIXA5GCcmlyYr84wlStep/KfWqrv+hS6yRJKyPNBsItUpFKtdLl8IG3EqDLhVzTsHBYHbq/AdZFxd5ImXeGzfTKKIBkHHlFd7kMxBZSsf+W34/LH0QRivg9VQqVcgw4qhFH/Qup74KjlsUmnOYLoK/2d/dRo9wdzbEIgucC+qz
    DRONE_RPC_SECRET: AgDq+9cab6eGpDwohvcqG18BsXmQmoQnTdG+7tUBCY3QU+D7V3B4jYaV3CSvuBMUdXl0r8Y6Ujc9GyUswSAzR7slLhtlqZzeh2Pe9bJbQL86b7ta376hKMMnupxFVfcEYvoszV0BoY4eiKqVOsG2xYuJYw83nJFY8HUq81NlXbnPeXLN2xA55XPQeH2IPuTlpbwF9BdipkLVTRha+ALSvWhZKaMStgXhognn8r+kyEKCaK4J7y+PtwzHKWtZPLcQslw+sorxtUlPkuGnFvnoPeYGW5cm9OSf+Rz75FyE8Xnffg6ScYym2PBGrm7A9/mj5jlOJRRuhRINtt3zSs3R28+NSmlwIMKSyNHthV7Fo/SUKNheBK/K+xkC/5dEWoOeHHC91bjKC4FZr8sKhH8z16bF/72LABASNZ8g1vt7lxCu8OCHsL03xzffSMGX0/zdcwLxvNeUTZzx4QH8SA0T91EjDhcCL6nZDMB8yXdyeQq86IQgq9WLENdy4xdzPOxRLZLlSCHCOvXb6h0aLgmO+coC/WtNtZ9mx+FIhxXX7f+/Srez0boxt5AZz5u1F1Yliez99NaN0njnWBQ41Wi+YCXBW7mHe9Sf4RAlYgGZ/FyVU7Iz5d4otSGDR+qlUx17oJ5cC2shVn9SxlWinpBl3tggWI0wzxY604uYqHfAJV7FcjMGjVGpQsOE+DaYyIO9nXvH99qH0fm1bvUT337OPf0+0ppWmufQ5ORhMO8f3CybiA==
  template:
    metadata:
      name: drone-server-secret
      namespace: devops
      labels:
        app: drone-server

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: drone-runner-kube-secret
  namespace: devops
spec:
  encryptedData:
    DRONE_RPC_SECRET: AgDKmx4WEpcWKSxAii9QsmhzjhwcF4J66JIaxMZC076LIk7wmMew1XtkkjKcf4ke5r5IWSdd6Or+7T+y5B86ZySBOB4/C0+u3ey5Gxci+wngM4YSEmhHbt+BTbYzF51s0bVJOtu+Dj6ozz5RIKVLzyLmhfRgW8Y+xVp8czHa/KOmkqDGyACgouNYTT3xbczgARB5cuJ+8uXyl+hv47zKq+k5mwRHQOwvms3NtZAhwigtY5ub68o71HDbfkxbbV2Ka5F2Nomztjs058a4CfJnznAyAkgzPbiIEfiN3o9q4OdL80EZ1yY/NLqqV3RI8MgGlABv77FpW/gZEs01yghoeanejrK0bba5p194t31r4a+57KTJGZYI4erTGo4VXGGSsEPz8JW0oNxxKnuRtZdIPQCQPJeJVHYNIOhnliutPfYLyGkPpYL/rphM8p8i1EZLrddPWJvKZEKhcDMp2/ZllmRg+lRLHifeFgJTmqlkVkIdJK148DRQ8TsSwV0BUn5C5dhcG3n+WXDPV8RlH4vld4hIyogkrOyviKLg57Tf85SxXykgg3W+p0tBJmI29YiaZb3kq5JU/DDPMHs3TLUP8Ejruh/DOr4DLT3GlPBhG6ylWZIXnhnFpJGlP32P6Kxp8uYv9GcxtSizcH9+eqrJPa4cVSbk4wKfQ1D6kMwrmjLTpdHoQPDFUI4jQCb9YHtydWjxdmd87ykeGRV0itWibOgM8KxO6KM4jBhKIASwwNyNlg==
    DRONE_SECRET_PLUGIN_TOKEN: AgBc+nWdQF0g7DPiyowVhBc0ix/o4Ik1SRxN5+P+NDdvDiKhwSsF9XqyngpqlWaUa5o95vvJ04BBs+4+RxR4HGFP8FvLPow5VXNliFvhrM/CHrvI3hOL0eBYNiH8g7880V9bRAz5wbrUNJ1J2e8MlaPWLOYqwlBDDjdfQNyBaE7/Qrz82U+yx0/2i1Odo5LUEWx6LCwmdrq/m6erDm6HZRJIM6zL3ADuWb2WAhscpdXfTakdTj95kZ/cja1LvtFujoIFVYKLgGRcYkUAGT3qz3yBHudpM3/9RzbLYfWPqmaoHb99YkK7QzGccpBIwtXv55+RAi29dRiqU+hwBBcIJ3cUeJNzGqAtmHSGsWT9E7NmWnfAuwU3SRKH3nYMraaKVvPtQiq9NP3u5CJm/869/Ysd12rGC+KirrrLzx4pGYRfMQqe/3s5tl20BTR5M6fe0vyQ66+vriTZYQhz7oTb+SshkRbph+PSb+nx2RTAkw6QLxv1VNc6y59T+68bFzW1gVtXFpbsRmO1KpIbNPela2dzSMaRhCnGf6C2a67V3u/iORZkCkfu+Huhx48uu5j5+FGsjgmNHJKUPidx7mugXs8A7AvTJ3mE+HZswDzUpAuElOhDCo81G8YHxTQsvPMKYlKgDfdsaHFxOwSm4gWVfbNJP6cH4ECLaWnztloFuUUB1KbhM/yYHIGd3t0JAqntzOj8WxqXLSSWfOPs5rodOhK/88ktmbyYKa9Sb9EKz7zt/Q==
  template:
    metadata:
      name: drone-runner-kube-secret
      namespace: devops
      labels:
        app: drone-runner-kube

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: drone-secrets-secret
  namespace: devops
spec:
  encryptedData:
    SECRET_KEY: AgAD/OhJL7TEd0OhAck+M4d+F5Ss6/SLRHQlsIQa1EBR+9AQbQx9qeiNmgq8ccFze8PVUqvVz2MYweB3UdkXCL8HHVbQOzyJXWUg9RrykvNFMJ/oOPABFT4fd6RmsJQDxwgv0z1WX3uhoIdU3O1DmCtQ21gcPgdXpfKo/w8sNTYxQXt7Cb8XbtTwgvgsFsnPS4yq6yDBk27VOMpZ4fLKf4SeNoa7wlAXS9bQWDWktnwB2jd6cdAMwkNfjuEZ8FlU+XGcvuxEkVPvkxHqSkCagNy1hNmX2Xd6QpNUhqftBGtdrRwumzQldDxdB/3iDP7Ujzocs/x5TpcPgLAs/DRcC9pEP6C58eXSOi6lqIojN/KFzm6R/3WrWLrZ2R4YOQlDvaGjBHjH/tPd4t+udxWbwt2dQhCEDdywkdS0klnfl374H7dgXnXk7bETATaVP3uBgATI+4UjnGoO1WFTsoNqmc/sWdcriPeiROHRs9HAKgkCz3T44dO6Uh9LrVujT1Sdg5KGSvlm2lt1vfIu5ie+KYdN/1p9SSdxBnA3osO3zjKrBMeh3ju8XLzBuYexHgzL4gMakOpe3q+xKrCAPOy6rOGrGE5bSOwJkHPdtBP2wkgso3bxMsHfzjp7HuUhvjnWw9+GZnv8WFbCGaZjAXEwgoMJjKPNjvNpx5gwZMNyJJxq/PPHmU9ZQDjUHv8/ft8tzJhpOOZn9sGaReqe4GL+F6AkwkhafCHUMTRad0WmrAVbEA==
  template:
    metadata:
      name: drone-secrets-secret
      namespace: devops
      labels:
        app: drone-secrets

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: github-ssh-keys
  namespace: devops
spec:
  encryptedData:
    id_rsa: AgDp62BjhLb0gFUTa5OEY2LkQgw5l6VALo/uT+vmp/tgWgh3BZwNXLw50kBLmABaFXa7KgqY7olJ0qGjcz1/stQcoFAqY7wHMfzq+tQxbOObZ96g+NxGJTmQaBSxp+q+9YIcb+8AMr1DRvNLmAZRlB3l5jZHSyyOdX0RM2UoIdXqCHHLkYPD0bjol3cwW/I4zgIL2a/+c3DDKe9fA6BazvxFKMdJ7dI4t8ldZ2+ZPNT/PNJtNKWLfT8LTfAY/fWbrIl0z2/AQ/DW990eoJm+WYpg+6uVpuaXaPG92Ehk/NGCzd0BQIH0aN/U9P7bQjJ/Afc0CvEL6u+D7aQ/7zlKq3IRNUggs7zIG60kHuUI9YruEGeKzWfS4OpB0rT/YmLZiNh08ntxAhKUeqsHUDIMydRoOVLD6xDLC6aCfzu0jSikdA3goKtPao4Ja5VipuAMnzuOcnh1w4R7ApDgX7y4elHuugfrsi3zOZlysuVJijXgjYzm2U8cJxNDXM4Ecw7InXhhZi0U/OmaO7Dj2lUTriFPUrzQdi0AyBIhIU/A4hgZzLVmKUqFD65bLj5REl47nCaEbNjBTfzkvL5azOJEznaZf2rhdMJ/7apSZd5ce/o2vSCLSL+Nd//PPhzV/1nSWRTdjJVkKGiJpymO0qimOhiMvbJLFaq2fYAJCB1XXCDIbHAwzMbiOy7UBZaJVopFI2OVzQbygf/12EWy9/7J5pXG+BWsjUZMcMGBhrrCGx6nLfllBSSG5/qqbT/cBsi2lV3EGkn0smv9TO2oyWgX8cp7d1/5jSDeEzAnDdwMZ1azM8ZZKh0pBwQ1LYKM4B8pkLFy3fsazzmQofY80uWSXWIUpOGIdjkEKP5hHM28bGOU4N5VVRqQZL4416mE8rlKsXrEhWNon0wNA8TGhDh+Z+nNpq4neqm4z/OZE2DvqcnQcspMnypvvloy5PVqP3gm9KBHU3fKUMYXjh24a5aP6pz00nKYC86CN4ELHv4YxlX4ri70U3ttYX5+z6Rs1M5aa3bX21c9Tz0bEiSOJtuINI8oawMXbQ6nVLCQtPAx9ukQgmVIGaQukIxF6wGTHqhv4btGEePgWG5z/oRHxXbWVi0BUYsrmiEuqmvsqJJbZAP2JgQ7gfxs2DPAIuUsN4DTOn7koPpm7O/XBIRF85dTfXn7h1C4EwSy82/pcXpGBVoaEQwtRB8mMZsOmGN3l5RZeP4wN3XhoiQKge0p3D9RP70kqVzhb8XxO3A9EptWZcXc0rtRyPxCJZvJZIsEQeoJIed36gJpxL2HEfn708uO4JP88ZBvnLcaQj0i4RbnkSLfplYUjIkaqt3hRhwhkYpK7whz5WZfcofdmZnhzMTprGw02ec3nhhhoAKvTrRImUubUdTDBbT4E/yZgF6ORnh0M3wF064/hyqPQ6RF8YvZQsQKshGdgtRSxw853glJKABNZ+fgaamklLq7A0EQ4O+7sNGGXCH0AhR6xRwbiRNVmUiJzmFvbBQbbWbKLvErtf7fbeOsWMCorhsPrsK1McTiQ5vTIUW232WuZCd4GDbo4nvGKv07YB6tCrPbDkogXvk7kH9SxGU7uk2Vr8/QZ6t1mFoEVKsxMcIF0j2epll5H+RCwSY3Cjue/nfEs1HL/leaGdUbtKpGlZ69FFbKEucQM9zejk9tiiFlt/ufm9i15/1Y3IFQOBqN/qCxP04+nuTMGqBN0gJoC2LDIJCrPiewFcyYhvfHDEmPSpRBPybN7ITOIYHKzCeYvT1Z4bqdCNuITDRyBaWUgw+XChbGcMsmTHAMtSowvNeTezbqP4JORj8Ipxifo91VvQ+czV0WnpoeEKlP4RGoeU1ucsccugGY2pEK4IoaS2mWKC6DyAcUNINxogyCj4MDWbu+BrJOjg9W3aEoR7mjbByQRnaGF5FK6ZsmWeM9Myae55i+fBrEc2r1Ex/9gR3ce8yYNAZTHWJYogCl9bFF3poCQ0QEGBCYOiYU254y+dKSlzVkYGKptu0EKPCfS9dowx1EfPvhk9vhSS/18iiaYW++/Bwo3Bunk+gs2hfv0JRokb21QDHd9dAsBoqqyJObXAcfrUuHGjBwXkrZdyOCKIh9ckp6QuWBtVg3k889bxJbDiRsBmytasXXVgqCAdKFl6QiwvXqLul4vstAgx5BVXfqWZy1LzrIzNJs5R/q9soXSv4zyV8GuTyJ+4qJKkUO5/XoV1L/Dg3OxafqGdMrweuXjZhmprQde2GET0JPz3tvxpo1uH0W0zOdGH4KexWFUrbOZkuj4mi+ngMs1+WHfFlp7Eyo8/tSkgqBBh5qx8+zsIdB8N8v2zqKEtHYIR25JK2za9ucH8pSaSwViqFDCxNW9l2ivzwcj9JS+J+n/TM5GO2BiJfsufL9yR3/HnT3FtHtk6n9uZgj1KhUfuTvZxixk3/jWmwK8FkFLBjef+aPJlKW/9dWqoxNi6MHHO1hB6/41PW9UK/IqCm9VqbvADUtAqhdkpwLJg+HtfmwxRHDZLpR7jolRSzDb26B10LpQx93MVbWLhmy89ZqcPqHjv0yThZvrhLlZg/blG0ojDc8MsmnZJWZxBAzNuY88qoE2ADQ7tlBJLLkJCQhaNzml/PRGbrNIzICh1E13r1V/BcuvHg4sUrh4wVNxlAGT/T/CuNeGn8A2nisCVSVWOtOUGiCbY7gytGzHRI44ukjjMBRZH4/81ehgeNWUWkeNOz39O7du2BJ5NEnlwtM9V+6Elj71CR7fx6CIhfUcQGf2viGNeeMVXRXND1QUUIvL7rprNBNTYdra8OkfXjzqFWPyG52QN2rbEf0EEgGO9CsULqwMV/6+wXFZcLO73xLHc7yONv93p0uIMwXZoqPFcZhJKxXS4VqJiazCcxvcosxhX/HB9zGNpU2d0ekP3IidoLcdXbn1K3pLzuuHxRLShr616ghd8ytHkCKxPFxHdti8uMgQq2+AIOG/LfhToY0qfUVC0fk24FrOS9DHcN65U0xFaxtU3MjaZ0mC3j7uha5SV1PA9XV2kkkpAaYvI1g4NyWl4oXi9qWEe2iSJmghWBJhqN15SbM8vgkLezb3uMBaDPrEEpVd76d3GnaLl/qJ7g2MkLHLabs/j8xM9tpyz6OQA1DX5rz6Ej0Pw==
    id_rsa.pub: AgAyrKKoHc+9Eskv9ZceFjQeia3ND7yv76l/VO2UuNVGlCn5kWllYVO1HRvhkl/7EdZBZwRJEo6hCQod2tCJYScHfhE9dV58TV9xKTUJjxR6lXrov4tvzaQ/LkNRHhJbTp/0k9EzzZ9nY9dYGRetV9eqITy17SSgwyLHxwo/7oKt+yV6CefN1OdE9KeYVdWGLULjnL/46hsLSPXYnShDoDadznu849f1QdqbqjTv2/7zOtQXB2nhmrf1VqdW+kgQz0nPg5uLm0Bs6bf8vMShTVPYCGPqVc5Jd8bHB2jWphpuYH4t2HHhdtrbFujC9f8sZXmgL3F5ftXqvOesnK4pPCCEGgJFn3wAvnVVmLCQ9XXbTYSheF2ELjWZ44uFTGO2l9jnDxIIOQ82XDk/w/QN9aA/5YTkzHis8lOgJ74mGuULAa50Rml2CpVEUwAAmWGFQJ+XDkIF9vrQey8Gsq8iWITIAxC+fjTpJgDs+u+KeJ3H/fAD8+vbQeSacg4EuNAcpJg1bS94JtbhalkuQTq6Vgwl8Zirn9LtJXtysrWU9A75gIMwr4ad0gNxwjR6+CJyxWBQqLqKH5gZvVxH3E/7HE/uhPTLuHfTnrXlmcpZSnboAcsJdqNl8MajcH3LZaPx6a671xCLflnzh05FNag/7GpkkmmbyIkqoLnMrmt5UJbYSH+7ESjAuyvowmHlw7G4o6hluW6ehSW8x56Pis3FFcHDEdt3qXMQ8RwcY4GWkoJgqqIP3mn+Pz9qELUCUwmwEtpnsvD9dHku2+Z52MeuN4ygYxhK/M2UCZD0DvM7IHSxfvaZlaDfdehj//sjdp1O9DCwCa/kN5vx+olUpoxwlHbXGKaKQQfem3eoU0IB27AFSiDBbT1BENd1jPwcHsL1UNTd2w44v7R8bixvg/I4ZYHwhGvJaDpcwMPmBQKvPsTge3Fe8lBljfsc5v1mc9qFfNKnyRecLnpfnr2dZcNPKziePKDvAuXe/H1kAFba85G/Dq19hGA/A4rXyqflVHluf0ZRbK720ScLce4uA1UMAmXQoWNF8I16lPxlg+zKcPYn/gAAgy+lED2LD5xISiFvvOQoH3i4itMHorll2S9aPrl6ucxyrymSz0jjANJAxIu/nmVwG6srHsxap4kgW+tlSC6SW7CEDN36aXeVUrdudo31qKxoEZkq5Ei6zt+TWL6t/wgFdGr+q7K11KFlWH2tWAKzQNisXPbDSkM8HCJF
  template:
    type: Opaque
    metadata:
      name: github-ssh-keys
      namespace: devops
      labels:
        app: drone-secrets

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: drone-server-config
  namespace: devops
data:
  DRONE_SERVER_HOST: "drone.theautomation.nl"
  DRONE_SERVER_PROTO: "https"
  DRONE_SERVER_PORT: ":80"
  DRONE_USER_CREATE: "username:theautomation,admin:true"
  DRONE_USER_FILTER: "theautomation"
  DRONE_TLS_AUTOCERT: "false"
  DRONE_LOGS_TRACE: "true"
  # DRONE_DATABASE_DRIVER=postgres
  # DRONE_DATABASE_DATASOURCE=postgres://root:password@1.2.3.4:5432/postgres?sslmode=disable

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: drone-runner-kube-config
  namespace: devops
  labels:
    app: drone-runner-kube
data:
  DRONE_NAMESPACE_DEFAULT: "devops"
  DRONE_RPC_HOST: "drone.theautomation.nl"
  DRONE_RPC_PROTO: "https"
  DRONE_LOGS_TRACE: "true"
  DRONE_SECRET_PLUGIN_ENDPOINT: "http://drone-secrets.devops.svc.cluster.local:3000"
  DRONE_DEBUG: "true"

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: drone-secrets-config
  namespace: devops
  labels:
    app: drone-runner-kube
data:
  KUBERNETES_NAMESPACE: "devops"
  DRONE_DEBUG: "true"

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: drone-server
  namespace: devops
  labels:
    app: drone-server

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: drone-runner-kube
  namespace: devops
  labels:
    app: drone-runner-kube

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: drone-secrets
  namespace: devops
  labels:
    app: drone-secrets

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone-runner-kube
  namespace: devops
  labels:
    app: drone-runner-kube
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - create
      - delete
      - list
      - watch
      - update

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone-secrets
  namespace: devops
  labels:
    app: drone-secrets
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone-runner-kube
  namespace: devops
  labels:
    app: drone-runner-kube
subjects:
  - kind: ServiceAccount
    name: drone-runner-kube
    namespace: devops
roleRef:
  kind: Role
  name: drone-runner-kube
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone-secrets
  namespace: devops
  labels:
    app: drone-secrets
subjects:
- kind: ServiceAccount
  name: drone-secrets
  namespace: devops
roleRef:
  kind: Role
  name: drone-secrets
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-server
  namespace: devops
  labels:
    app: drone-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-server
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      automountServiceAccountToken: false
      serviceAccountName: drone-server
      containers:
        - name: drone-server
          image: "drone/drone:2"
          resources: {}
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: drone-server-config
            - secretRef:
                name: drone-server-secret
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          volumeMounts:
            - name: drone-server-data
              mountPath: /data
              subPath: ""
      volumes:
        - name: drone-server-data
          persistentVolumeClaim:
            claimName: pvc-iscsi-drone-server-data

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-runner-kube
  namespace: devops
  labels:
    app: drone-runner-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-runner-kube
  template:
    metadata:
      labels:
        app: drone-runner-kube
    spec:
      serviceAccountName: drone-runner-kube
      terminationGracePeriodSeconds: 3600
      containers:
        - name: drone-runner-kube
          image: "drone/drone-runner-kube:latest"
          resources: {}
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: drone-runner-kube-config
            - secretRef:
                name: drone-runner-kube-secret

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: drone-secrets
  namespace: devops
  labels:
    app: drone-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-secrets
  template:
    metadata:
      labels:
        app: drone-secrets
    spec:
      serviceAccountName: drone-secrets
      containers:
        - name: drone-secrets
          image: drone/kubernetes-secrets:latest
          resources: {}
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: drone-secrets-config
            - secretRef:
                name: drone-secrets-secret

---
kind: Service
apiVersion: v1
metadata:
  name: drone-server-svc
  namespace: devops
  labels:
    app: drone-server
spec:
  selector:
    app: drone-server
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: drone-runner-kube
  namespace: devops
  labels:
    app: drone-runner-kube
spec:
  selector:
    app: drone-runner-kube
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name: drone-secrets
  namespace: devops
  labels:
    app: drone-secrets
spec:
  selector:
    app: drone-secrets
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000  

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: drone-server
  namespace: devops
  labels:
    app: drone-server
spec:
  ingressClassName: nginx-public
  rules:
    - host: "drone.theautomation.nl"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: drone-server-svc
                port:
                  number: 8080
  tls:
    - hosts:
        - drone.theautomation.nl
      secretName: cloudflare-tls
