---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-test
spec:
  storageClassName: "freenas-smb-manual-csi"
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    nodeStageSecretRef:
      name: smbcredentials-coen
      namespace: democratic-csi
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: cifs
    volumeHandle: smb-test
    volumeAttributes:
      server: storage-server.lan
      share: coen
      node_attach_driver: smb
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-test-data
  labels:
    app: test-app
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-smb-manual-csi"
spec:
  storageClassName: freenas-smb-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: smb-test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: test
              mountPath: /mnt/
      volumes:
        - name: test
          persistentVolumeClaim:
            claimName: pvc-smb-test-data
