kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: home-assistant-config-check
  namespace: devops
spec:
  workspaces:
    - name: source
  params:
    - name: containerImage
      type: string
      default: "homeassistant/home-assistant:latest"
    - name: args
      type: array
      default: ["--help"]
  steps:
    - name: config-check
      image: "$(params.containerImage)"
      workingDir: $(workspaces.source.path)
      command:
        - hass
      args:
        - $(params.args)
