kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: home-assistant-rename-secret
  namespace: devops
spec:
  workspaces:
    - name: source
  steps:
    - name: rename-example-secret
      image: alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        mv ./src/config/secrets.yaml.example ./src/config/secrets.yaml
        mv ./src/config/google_assistant/google_service_account.json.example ./src/config/google_assistant/google_service_account.json
