kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: home-assistant
  namespace: devops
spec:
  description: >-
    This task does a configuration check of the Home Assistant yaml files.
  workspaces:
    - name: home-assistant-code
      description: A workspace that contains the fetched git repository.
  params:
    - name: containerImage
      type: string
      default: "homeassistant/home-assistant:latest"
    - name: args
      type: array
      description: extra args needs to append
      default: ["--help"]
  steps:
    - name: config-check
      image: "$(params.containerImage)"
      workingDir: $(workspaces.home-assistant-code.path)
      command:
        - hass
      args:
        - $(params.args)
