kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: rename-secret
  namespace: devops
spec:
  workspaces:
    - name: home-assistant-code
      description: A workspace that contains the fetched git repository.
  steps:
    - name: rename-example-secret
      image: alpine
      workingDir: $(workspaces.home-assistant-code.path)
      script: |
        #!/bin/sh
        mv ./src/config/secrets.yaml.example ./src/config/secrets.yaml
        mv ./src/config/google_assistant/google_service_account.json.example ./src/config/google_assistant/google_service_account.json
