kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: prettier
  namespace: devops
spec:
  workspaces:
    - name: source
      mountPath: /source
  params:
    - name: args
      type: array
      description: Prettier arguments used to run Prettier.
      default:
        - "--check"
        - "."
    - name: image
      type: string
      default: docker.io/elnebuloso/prettier:latest
  steps:
    - name: check
      image: $(params.image)
      workingDir: "$(workspaces.source.path)"
      command: [prettier]
      args: ["$(params.args[*])"]
