hostname: k3s-template-xx
k3os:
  modules:
    - kvm
    - nvme
  dns_nameservers:
    - 1.1.1.1
    - 1.0.0.1
  ntp_servers:
    - 0.nl.pool.ntp.org
    - 1.nl.pool.ntp.org
  password: rancher
  token: TOKEN_VALUE
  k3s_args:
    - server
    - "--datastore-endpoint=postgres://k3s:<PASSWORD HERE>@k3s-postgresql.lan:5432/k3s"
    - "--cluster-init"
    - "--disable=traefik"
    - "--no-deploy servicelb"
