---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-drone-server-data
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-drone-server-data
    volumeAttributes:
      portal: storage-server.lan:3260
      iqn: iqn.2005-10.org.freenas.ctl:drone-server-data
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-drone-server-data
  namespace: devops
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-iscsi-manual-csi"
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: pv-iscsi-drone-server-data

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: drone-server-secret
  namespace: devops
spec:
  encryptedData:
    DRONE_GITHUB_CLIENT_ID: AgCYM7K6a+KrooUE1Zcf0MG8KhnWaZEg5H2+Zfp4MC/TyGxUkco4++fu/iwoIvmanYrCb+vppOfUrgGuTFWNj0n7+uEYk5uiNXsZLUAtoKClmDGrzwrxIeTfC3/sG3r84Kn8u3INXR2xSSevi0sbRAoOTtFn+G4K0B+iyZgND7MsbYupihnjTpzk+gDT5ROQwkL++RQrqcsTXLcNHnR+UJOojDL+HD/KiLbbR8LTwsEtB7JCtc94wj9rj0O6x/KuW1fIy5IL3BLMpviPtad6+uXChLi3/+dSqa6PWUPx1nO0k+8UYK1J8HHU5O3qVgMxxrNlT7HJq839aWb5xzTUk3G/Wi/Rr/vn4h+9+tEvAorwRxurX3yMkO6Yyfa1uJyif4fwT/gDAMMDj+SyzK3jn5FOPddc/aTjv/HHueQrWo9ErKPUOjKW7o/ril7OCXJ9dCfXGG7wTu7mJaBMrJdjOgAcm0OW/hEts6k7s+E5KH32zgkd7HPixIJuYpnNfPHbpeo5v5DPYOpveY5kv/NGRkZwmN5IlwP1buHBsSX4NYhJTcRLRRaXH05BKJtbgbvGzRaVGl5ThxmA/lERrCKWPqX9G3hi6w/fjZlW10CzbDAsDcqiiJJ7c1SybqknGMFH9oFR9+ukOKge2YJTrE1D33xv6cLogriLgZojKUVVES+O85KAzUXWszJNAzzdM6EMwz/IwbHLIvj3P4/LW/73vRef6uqNhw==
    DRONE_GITHUB_CLIENT_SECRET: AgC6ehEAnvaMNs+Uews1hzhGMHMbE7lX+5qX7fADpK8nebUBHq2HWU5uNCY7hV9OEdTQiFDujyGeYyULpI2kdnBZZ495NkxjcOo0VRMP2wxQIpBAzQ64o010a7nHlByOeebSxddqNdzTKBIdCIU5y/QaorQN4ozRdsaxQA9Bu49FRLgPRcxdjaVtwCnbHIPTTqi3mxOTCRDlddpuE9ZFtK36HYe/GKjgI7VRg3wqSIK3dOLzTgDvEpswRI94ofHAdOzqOkyaPaBPyXQNp0z/C8QtfkH8+/ZBk7hvzclPi+ztQ9ays/wYzeWog1sUAlUtvjqFCvHFrkr0K34HVfOqPWRzH/8GWl3quT0cXw4FcfawqiVphe6CXhGdOQAexNXVbsCyoY14/LoyRmgZL6BmTW4ZJCVlbDmtfPfVY95JTI55oWpks6EXfEcuprucd3RWUTikZFkDmizcbNDbJjAG3uTv+lyCft1jGnJDxnVmiEFOJV8WygMP7q6NAdsyNr8beDIK3zNXSWfxybGz4SXcliFnS49sfGffL8G+E523tUD2UC6h6BHa1uMaYrEVWfnxN3AUymhfj9wJAOnIXA5GCcmlyYr84wlStep/KfWqrv+hS6yRJKyPNBsItUpFKtdLl8IG3EqDLhVzTsHBYHbq/AdZFxd5ImXeGzfTKKIBkHHlFd7kMxBZSsf+W34/LH0QRivg9VQqVcgw4qhFH/Qup74KjlsUmnOYLoK/2d/dRo9wdzbEIgucC+qz
    DRONE_RPC_SECRET: AgDq+9cab6eGpDwohvcqG18BsXmQmoQnTdG+7tUBCY3QU+D7V3B4jYaV3CSvuBMUdXl0r8Y6Ujc9GyUswSAzR7slLhtlqZzeh2Pe9bJbQL86b7ta376hKMMnupxFVfcEYvoszV0BoY4eiKqVOsG2xYuJYw83nJFY8HUq81NlXbnPeXLN2xA55XPQeH2IPuTlpbwF9BdipkLVTRha+ALSvWhZKaMStgXhognn8r+kyEKCaK4J7y+PtwzHKWtZPLcQslw+sorxtUlPkuGnFvnoPeYGW5cm9OSf+Rz75FyE8Xnffg6ScYym2PBGrm7A9/mj5jlOJRRuhRINtt3zSs3R28+NSmlwIMKSyNHthV7Fo/SUKNheBK/K+xkC/5dEWoOeHHC91bjKC4FZr8sKhH8z16bF/72LABASNZ8g1vt7lxCu8OCHsL03xzffSMGX0/zdcwLxvNeUTZzx4QH8SA0T91EjDhcCL6nZDMB8yXdyeQq86IQgq9WLENdy4xdzPOxRLZLlSCHCOvXb6h0aLgmO+coC/WtNtZ9mx+FIhxXX7f+/Srez0boxt5AZz5u1F1Yliez99NaN0njnWBQ41Wi+YCXBW7mHe9Sf4RAlYgGZ/FyVU7Iz5d4otSGDR+qlUx17oJ5cC2shVn9SxlWinpBl3tggWI0wzxY604uYqHfAJV7FcjMGjVGpQsOE+DaYyIO9nXvH99qH0fm1bvUT337OPf0+0ppWmufQ5ORhMO8f3CybiA==
  template:
    metadata:
      name: drone-server-secret
      namespace: devops
      labels:
        app: drone-server

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: drone-runner-kube-secret
  namespace: devops
spec:
  encryptedData:
    DRONE_RPC_SECRET: AgDKmx4WEpcWKSxAii9QsmhzjhwcF4J66JIaxMZC076LIk7wmMew1XtkkjKcf4ke5r5IWSdd6Or+7T+y5B86ZySBOB4/C0+u3ey5Gxci+wngM4YSEmhHbt+BTbYzF51s0bVJOtu+Dj6ozz5RIKVLzyLmhfRgW8Y+xVp8czHa/KOmkqDGyACgouNYTT3xbczgARB5cuJ+8uXyl+hv47zKq+k5mwRHQOwvms3NtZAhwigtY5ub68o71HDbfkxbbV2Ka5F2Nomztjs058a4CfJnznAyAkgzPbiIEfiN3o9q4OdL80EZ1yY/NLqqV3RI8MgGlABv77FpW/gZEs01yghoeanejrK0bba5p194t31r4a+57KTJGZYI4erTGo4VXGGSsEPz8JW0oNxxKnuRtZdIPQCQPJeJVHYNIOhnliutPfYLyGkPpYL/rphM8p8i1EZLrddPWJvKZEKhcDMp2/ZllmRg+lRLHifeFgJTmqlkVkIdJK148DRQ8TsSwV0BUn5C5dhcG3n+WXDPV8RlH4vld4hIyogkrOyviKLg57Tf85SxXykgg3W+p0tBJmI29YiaZb3kq5JU/DDPMHs3TLUP8Ejruh/DOr4DLT3GlPBhG6ylWZIXnhnFpJGlP32P6Kxp8uYv9GcxtSizcH9+eqrJPa4cVSbk4wKfQ1D6kMwrmjLTpdHoQPDFUI4jQCb9YHtydWjxdmd87ykeGRV0itWibOgM8KxO6KM4jBhKIASwwNyNlg==
    DRONE_SECRET_PLUGIN_TOKEN: AgBc+nWdQF0g7DPiyowVhBc0ix/o4Ik1SRxN5+P+NDdvDiKhwSsF9XqyngpqlWaUa5o95vvJ04BBs+4+RxR4HGFP8FvLPow5VXNliFvhrM/CHrvI3hOL0eBYNiH8g7880V9bRAz5wbrUNJ1J2e8MlaPWLOYqwlBDDjdfQNyBaE7/Qrz82U+yx0/2i1Odo5LUEWx6LCwmdrq/m6erDm6HZRJIM6zL3ADuWb2WAhscpdXfTakdTj95kZ/cja1LvtFujoIFVYKLgGRcYkUAGT3qz3yBHudpM3/9RzbLYfWPqmaoHb99YkK7QzGccpBIwtXv55+RAi29dRiqU+hwBBcIJ3cUeJNzGqAtmHSGsWT9E7NmWnfAuwU3SRKH3nYMraaKVvPtQiq9NP3u5CJm/869/Ysd12rGC+KirrrLzx4pGYRfMQqe/3s5tl20BTR5M6fe0vyQ66+vriTZYQhz7oTb+SshkRbph+PSb+nx2RTAkw6QLxv1VNc6y59T+68bFzW1gVtXFpbsRmO1KpIbNPela2dzSMaRhCnGf6C2a67V3u/iORZkCkfu+Huhx48uu5j5+FGsjgmNHJKUPidx7mugXs8A7AvTJ3mE+HZswDzUpAuElOhDCo81G8YHxTQsvPMKYlKgDfdsaHFxOwSm4gWVfbNJP6cH4ECLaWnztloFuUUB1KbhM/yYHIGd3t0JAqntzOj8WxqXLSSWfOPs5rodOhK/88ktmbyYKa9Sb9EKz7zt/Q==
  template:
    metadata:
      name: drone-runner-kube-secret
      namespace: devops
      labels:
        app: drone-runner-kube

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: drone-secrets-secret
  namespace: devops
spec:
  encryptedData:
    SECRET_KEY: AgAD/OhJL7TEd0OhAck+M4d+F5Ss6/SLRHQlsIQa1EBR+9AQbQx9qeiNmgq8ccFze8PVUqvVz2MYweB3UdkXCL8HHVbQOzyJXWUg9RrykvNFMJ/oOPABFT4fd6RmsJQDxwgv0z1WX3uhoIdU3O1DmCtQ21gcPgdXpfKo/w8sNTYxQXt7Cb8XbtTwgvgsFsnPS4yq6yDBk27VOMpZ4fLKf4SeNoa7wlAXS9bQWDWktnwB2jd6cdAMwkNfjuEZ8FlU+XGcvuxEkVPvkxHqSkCagNy1hNmX2Xd6QpNUhqftBGtdrRwumzQldDxdB/3iDP7Ujzocs/x5TpcPgLAs/DRcC9pEP6C58eXSOi6lqIojN/KFzm6R/3WrWLrZ2R4YOQlDvaGjBHjH/tPd4t+udxWbwt2dQhCEDdywkdS0klnfl374H7dgXnXk7bETATaVP3uBgATI+4UjnGoO1WFTsoNqmc/sWdcriPeiROHRs9HAKgkCz3T44dO6Uh9LrVujT1Sdg5KGSvlm2lt1vfIu5ie+KYdN/1p9SSdxBnA3osO3zjKrBMeh3ju8XLzBuYexHgzL4gMakOpe3q+xKrCAPOy6rOGrGE5bSOwJkHPdtBP2wkgso3bxMsHfzjp7HuUhvjnWw9+GZnv8WFbCGaZjAXEwgoMJjKPNjvNpx5gwZMNyJJxq/PPHmU9ZQDjUHv8/ft8tzJhpOOZn9sGaReqe4GL+F6AkwkhafCHUMTRad0WmrAVbEA==
  template:
    metadata:
      name: drone-secrets-secret
      namespace: devops
      labels:
        app: drone-secrets

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: drone-server-config
  namespace: devops
data:
  DRONE_SERVER_HOST: "drone.theautomation.nl"
  DRONE_SERVER_PROTO: "https"
  DRONE_SERVER_PORT: ":80"
  DRONE_USER_CREATE: "username:theautomation,admin:true"
  DRONE_USER_FILTER: "theautomation"
  DRONE_TLS_AUTOCERT: "false"
  DRONE_LOGS_TRACE: "true"
  # DRONE_DATABASE_DRIVER=postgres
  # DRONE_DATABASE_DATASOURCE=postgres://root:password@1.2.3.4:5432/postgres?sslmode=disable

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: drone-runner-kube-config
  namespace: devops
  labels:
    app: drone-runner-kube
data:
  DRONE_NAMESPACE_DEFAULT: "devops"
  DRONE_RPC_HOST: "drone.theautomation.nl"
  DRONE_RPC_PROTO: "https"
  DRONE_LOGS_TRACE: "true"
  DRONE_SECRET_PLUGIN_ENDPOINT: "http://drone-secrets.devops.svc.cluster.local:3000"
  DRONE_DEBUG: "true"

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: drone-secrets-config
  namespace: devops
  labels:
    app: drone-runner-kube
data:
  KUBERNETES_NAMESPACE: "devops"
  DRONE_DEBUG: "true"

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: drone-server
  namespace: devops
  labels:
    app: drone-server

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: drone-runner-kube
  namespace: devops
  labels:
    app: drone-runner-kube

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: drone-secrets
  namespace: devops
  labels:
    app: drone-secrets

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone-runner-kube
  namespace: devops
  labels:
    app: drone-runner-kube
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - create
      - delete
      - list
      - watch
      - update

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone-secrets
  namespace: devops
  labels:
    app: drone-secrets
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - watch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone-runner-kube
  namespace: devops
  labels:
    app: drone-runner-kube
subjects:
  - kind: ServiceAccount
    name: drone-runner-kube
    namespace: devops
roleRef:
  kind: Role
  name: drone-runner-kube
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone-secrets
  namespace: devops
  labels:
    app: drone-secrets
subjects:
- kind: ServiceAccount
  name: drone-secrets
  namespace: devops
roleRef:
  kind: Role
  name: drone-secrets
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-server
  namespace: devops
  labels:
    app: drone-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-server
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      automountServiceAccountToken: false
      serviceAccountName: drone-server
      containers:
        - name: drone-server
          image: "drone/drone:2.12.1"
          resources: {}
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: drone-server-config
            - secretRef:
                name: drone-server-secret
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          volumeMounts:
            - name: drone-server-data
              mountPath: /data
              subPath: ""
      volumes:
        - name: drone-server-data
          persistentVolumeClaim:
            claimName: pvc-iscsi-drone-server-data

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-runner-kube
  namespace: devops
  labels:
    app: drone-runner-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-runner-kube
  template:
    metadata:
      labels:
        app: drone-runner-kube
    spec:
      serviceAccountName: drone-runner-kube
      terminationGracePeriodSeconds: 3600
      containers:
        - name: drone-runner-kube
          image: "drone/drone-runner-kube:1.0.0-rc.3"
          resources: {}
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: drone-runner-kube-config
            - secretRef:
                name: drone-runner-kube-secret

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: drone-secrets
  namespace: devops
  labels:
    app: drone-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-secrets
  template:
    metadata:
      labels:
        app: drone-secrets
    spec:
      serviceAccountName: drone-secrets
      containers:
        - name: drone-secrets
          image: drone/kubernetes-secrets:latest
          resources: {}
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: drone-secrets-config
            - secretRef:
                name: drone-secrets-secret

---
kind: Service
apiVersion: v1
metadata:
  name: drone-server-svc
  namespace: devops
  labels:
    app: drone-server
spec:
  selector:
    app: drone-server
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: drone-runner-kube
  namespace: devops
  labels:
    app: drone-runner-kube
spec:
  selector:
    app: drone-runner-kube
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name: drone-secrets
  namespace: devops
  labels:
    app: drone-secrets
spec:
  selector:
    app: drone-secrets
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: drone-server
  namespace: devops
  labels:
    app: drone-server
spec:
  ingressClassName: nginx-public
  rules:
    - host: "drone.theautomation.nl"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: drone-server-svc
                port:
                  number: 8080
  tls:
    - hosts:
        - drone.theautomation.nl
      secretName: cloudflare-tls
