name: Check release

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  NAME: Ingress NGINX Controller
  ASSIGNEES: x-real-ip
  LABELS: update,todo
  TARGET_REPO: kubernetes/ingress-nginx

jobs:
  check-release:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get latest release
        id: get_release
        run: |
          RELEASE_API="https://api.github.com/repos/$TARGET_REPO/releases/latest"
          latest=$(curl -s "$RELEASE_API" | jq -r .tag_name)
          echo "latest=$latest" >> $GITHUB_OUTPUT

      - name: Check if issue already exists (open or closed)
        id: issue_check
        run: |
          exists=$(gh issue list \
            --repo "$GH_REPO" \
            --state all \
            --search "$NAME release ${{ steps.get_release.outputs.latest }}" \
            --json number \
            --jq '.[0].number')
          echo "exists=$exists" >> $GITHUB_OUTPUT

      - name: Create issue if new release
        if: steps.issue_check.outputs.exists == ''
        run: |
          BODY="### New $NAME release

          A new $NAME release is available: **${{ steps.get_release.outputs.latest }}**
          Update $NAME ingress controller to the latest version"

          gh issue create \
            --title "New $NAME release: ${{ steps.get_release.outputs.latest }}" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY"
