---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      nodeSelector:
        usb-dev: true
      containers:
        - image: ghcr.io/home-assistant/home-assistant:stable
          name: homeassistant
          volumeMounts:
            - mountPath: "/config"
              name: homeassistant-storage
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-recorder-pass
                  key: password
      volumes:
        - name: homeassistant-storage
          nfs:
            server: storage-server.lan
            path: "/r10_8tb/services/homeassistant"
        - name: ha-mysql-storage
          hostPath:
            path: /opt/ha-mysql
            type: DirectoryOrCreate
          volumeMounts:
            - name: ha-mysql-storage
              mountPath: /var/lib/mysql

---
kind: Service
apiVersion: v1
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
    - protocol: TCP
      port: 8123
      name: http

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: homeassistant-ingress
  namespace: homeassistant
  annotations:
spec:
  rules:
    - host: jeeves.harmony.arkane-systems.lan
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: homeassistant
                port:
                  number: 8123
